branches:
  - stable
  # - main

#// TODO: UPDATE!
repositoryUrl: https://github.com/emme1444/release_workflow_test

plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
  - "@semantic-release/changelog"
  - semantic-release-flutter
  # - "@semantic-release/github"
  - - "@semantic-release/github"
    - assets:
        # - path: build/app/outputs/bundle/release/app-release.aab
        #   name: web-schedule-v${nextRelease.gitTag}.aab
        # - path: build/app/outputs/flutter-apk/app-release.apk
        # TODO: This should be aab
        - path: app-release.apk
          name: release_workflow_test_${nextRelease.gitTag}.apk
          #// TODO: find path of iOS build
        # - path: build/app/outputs/bundle/release/app-release.app
        #
        # - path: app-release.app
        #   name: release_workflow_test_${nextRelease.gitTag}.app
        - path: app-release.ipa
          name: release_workflow_test_${nextRelease.gitTag}.ipa
