name: Callable Build

on:
  workflow_call:

jobs:
  # TODO: This job only builds for all operating systems in debug mode,
  #       without code-signing and all that stuff. Just to verify that
  #       the push or pr is buildable.
  build:
    # name: Build ${{ matrix.name }}
    name: Build
    # TODO: This should run in a matrix
    runs-on: macos-11
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     includes:
    #       - name: Android
    #         target: android
    #         build_target: appbundle
    #       - name: iOS
    #         target: ios
    #         build_target: ios
    steps:
      - run: echo Building
