name: Main - Test, Build and Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/callable-test.yaml

  build:
    name: Build
    uses: ./.github/workflows/callable-build.yaml

  release:
    name: Release
    needs:
      - test
      - build
    uses: ./.github/workflows/callable-create-release.yaml
