name: PR - Test and Build

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    uses: ./.github/workflows/callable-test.yaml

  build:
    name: Build
    uses: ./.github/workflows/callable-build.yaml
