name: Publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    # TODO: Should this run in a matrix? Can it?
    steps:
      - run: echo Publishing v${{ github.event.release.tab_name }}
