name: Publish

on:
  release:
    types:
      - published

# TODO: Still unsure how we're gonna transfer the builds?
#       Explore if we can use upload/download-artifact between workflows!
jobs:
  publish:
    name: Publish
    # TODO: I think this should run in a matrix
    runs-on: macos-11
    steps:
      - run: echo Publishing v${{ github.event.release.tag_name }}
